### ISSUE TITLE
No LICENSE.md file

### ISSUE THREAD

**Issue by matthewpersico** [Opticos/OpenInWSL-Source#11]
Would love to use this at work, but can't. Can you put a license file in the repo?

**Comment by Pololot64** [comment]
Hey Matthew. Look in assets/Licenses1.txt
[Licenses1.txt](https://github.com/Opticos/OpenInWSL-Source/blob/main/assets/Licenses1.txt)

**Comment by matthewpersico** [comment]
The auto license checker should find that...

**Comment by Pololot64** [comment]
That is strange. Maybe I can manually assign it

**Comment by Pololot64** [comment]
Now it is in LICENSE.MD as well

**Comment by matthewpersico** [comment]
> The auto license checker should find that...

I'm sorry - I meant the auto license checker at my job, not anything here on GitHub.

**Comment by matthewpersico** [comment]
But thank you - that **will** make things easier.
