### ISSUE TITLE
Consider not assigning file associations by default

### ISSUE THREAD

**Issue by blakeNaccarato** [Opticos/OpenInWSL-Source#13]
Upon installing OpenInWSL from the Microsoft Store, very many file extensions were associated with OpenInWSL. Quite a few of these filetypes are not specific to WSL/Linux/etc., but are filetypes any developer would encounter every day. They shouldn't be associated with OpenInWSL by default.

**Comment by Pololot64** [comment]
This is the way it has to work for open in wsl to show up in the "open with" menu unfortunately.
