### ISSUE TITLE
unable to add new association

### ISSUE THREAD

**Issue by qualname** [Opticos/OpenInWSL-Source#3]
Hey,
I'm unable to save new associations in the Association Editor window.

### Observed behaviour:
After going thru the following steps:  
- click `Manage File Associations`
- click `Add Association` => "Extension Input" opens up
- type an extension here and click `Ok`
- "**Association Editor**" opens up
On this panel both "App List" and "Save Configuration" buttons are unresponsive. Clicking them does seemingly nothing.

### The logs:
```
2021-07-19 15:09:29,144 - OpenInWsl 1.3 store - ERROR - cannot save edited assoc
Traceback (most recent call last):
    File "main.py", line 1015, in saver
AttributeError: 'Label' object has no attribute 'get'
```

### Potential issue:
[In the source](https://github.com/Opticos/OpenInWSL-Source/blob/7b68103c1cdf2dee651925f99b5738b579a8f3db/main.py#L957  ) `machine_chooser`'s type is different depending on how many installed linux instances there are (one or more). Either `tkinter.Label` or `tkinter.Combobox`. The 2 classes provide different interfaces. Some functions are not supported by `tkinter.Label`.

**Comment by Pololot64** [comment]
Thanks for the report! I am assuming the test config button has the same issue too?

**Comment by Pololot64** [comment]
Fixed! Will repackage soon

**Comment by qualname** [comment]
Thanks for getting on it so quickly! :)

**Comment by Pololot64** [comment]
:)

**Comment by Pololot64** [comment]
I submitted the update to the store today. It should be out tomorrow.

**Comment by Pololot64** [comment]
The fix release is out
