### ISSUE TITLE
Feature request: Open web links

### ISSUE THREAD

**Issue by adouzzy** [Opticos/OpenInWSL-Source#4]
Is it possible to open web links in wsl?
So far I can bind .html but not https:/xx.xx.xx
Thanks

**Comment by Pololot64** [comment]
It is possible to implement but I am not able to release an update for a while. Also, since every browser runs on every os, I am hesitant if this is actually useful XD I'll leave this open if anything develops but I do not think I will add it. (Unless a super important  use case comes up haha)

**Comment by Pololot64** [comment]
Actually... if you want to get hacky. Maybe you can try doing this XD. Make an association for a filetype like this ```./?``` and point it to a browser in linux. Those characters should be ignored by the browser or website. Then run ```oiw.exe (url)./?``` (without parentheses).  This is hacky like I said but *may* work haha

**Comment by Pololot64** [comment]
But at this point you could also just run ```wsl.exe firefox url``` lol

**Comment by adouzzy** [comment]
Fair enough. Understand your pain. I will give it a go.
